# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38f65ad4e777fb85fbe17fc2fc7ad98f44b015073064b3c496788deacb4eb97b59549a1388abe065c47630afcc1c9e4a33e1ebb3ad4047b76ae23f2238cb0d6c

test:
  secret_key_base: e43a9e5e146a074fa82dc66d4a583ce995bb3171bcf9f7529dcc897dd27ce7fcfbdfc67250b757771ad52fe26d7f1b46bb4b814c96c4ede0461d5ac4f23b5ebb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
